### ISSUE TITLE
selmer fails to install

### ISSUE THREAD

**Issue by licht1stein** [nextjournal/garden-cli#6]
I'm trying to deploy my project, and get the following error:

```
Pushing code to garden...
Current deployment stopped.
Starting new deployment...
Error building classpath. Failed to read artifact descriptor for selmer:selmer:jar:1.12.61
org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for selmer:selmer:jar:1.12.61
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:255)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.readArtifactDescriptor(DefaultRepositorySystem.java:263)
	at clojure.tools.deps.extensions.maven$read_descriptor.invokeStatic(maven.clj:115)
	at clojure.tools.deps.extensions.maven$fn__1320.invokeStatic(maven.clj:143)
	at clojure.tools.deps.extensions.maven$fn__1320.invoke(maven.clj:143)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at clojure.tools.deps$expand_deps$children_task__928$fn__930$fn__931.invoke(deps.clj:407)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:671)
	at clojure.core$bound_fn_STAR_$fn__5818.doInvoke(core.clj:2020)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact selmer:selmer:pom:1.12.61 from/to central (https://repo1.maven.org/maven2/): /deps-cache/.m2/selmer/selmer/1.12.61/selmer-1.12.61.pom.part.lock (No such file or directory)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:431)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:235)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:212)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:240)
	... 23 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact selmer:selmer:pom:1.12.61 from/to central (https://repo1.maven.org/maven2/): /deps-cache/.m2/selmer/selmer/1.12.61/selmer-1.12.61.pom.part.lock (No such file or directory)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:52)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:401)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder.lambda$wrap$0(RunnableErrorForwarder.java:73)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:669)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:290)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:408)
	... 26 more
Caused by: java.io.FileNotFoundException: /deps-cache/.m2/selmer/selmer/1.12.61/selmer-1.12.61.pom.part.lock (No such file or directory)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:356)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:273)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:223)
	at org.eclipse.aether.connector.basic.PartialFile$LockFile.tryLock(PartialFile.java:138)
	at org.eclipse.aether.connector.basic.PartialFile$LockFile.lock(PartialFile.java:82)
	at org.eclipse.aether.connector.basic.PartialFile$LockFile.<init>(PartialFile.java:70)
	at org.eclipse.aether.connector.basic.PartialFile$Factory.newInstance(PartialFile.java:268)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:481)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:396)
	... 31 more

ERROR: your project could not be started.
```

**Comment by licht1stein** [comment]
deps.edn dependency is `selmer/selmer {:mvn/version "1.12.61"}`, locally everything works just fine
